title: "OctaPi: public key cryptography"
hero_image: images/banner.png
description: Learn about the concepts behind public key cryptography
theme: violet
listed: true
duration: 3
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: cybersecurity-and-cryptography
technologies: raspberry-pi, python
hardware: raspberry-pi
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What is public key cryptography?
- title: How can a key be public?
- title: How are public and private keys chosen?
- title: Challenge: Finding factors
- title: Generating a public key
- title: Spot the weaknesses
- title: Finding prime factors on a single Raspberry Pi
- title: Finding prime factors on the OctaPi
- title: Can I hack with my OctaPi?
